const mongoose = require("mongoose");

/* One-click login — one-time codes generated by the admin panel.
   The admin opens the client app with the code; the client exchanges it for
   a normal 7-day session token. Codes are single-use and expire in 7 days. */
const LoginCodeSchema = new mongoose.Schema(
  {
    code: { type: String, required: true, unique: true, index: true },
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    used: { type: Boolean, default: false },
    usedAt: { type: Date, default: null },
    expiresAt: { type: Date, required: true },
  },
  { timestamps: true }
);

module.exports = mongoose.model("LoginCode", LoginCodeSchema);
